apiVersion: apps/v1
kind: Deployment
metadata:
  name: saldo-deployment
  labels:
    app: saldo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saldo
  template:
    metadata:
      labels:
        app: saldo
    spec:
      serviceAccountName: default
      containers:
        - name: saldo-container
          image: gcr.io/trusty-equinox-459800-k0/saldo-service
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '100m'
              memory: '128Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: saldo-service
spec:
  selector:
    app: saldo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saldo-ingress
  annotations:
    kubernetes.io/ingress.class: 'gce'
spec:
  rules:
    - http:
        paths:
          - path: /updateSaldo
            pathType: Prefix
            backend:
              service:
                name: saldo-service
                port:
                  number: 80
